export default {
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAILED: 'REGISTER_USER_FAILED',
    LOGIN_USER_DEFAULT_SUCCESS: 'LOGIN_USER_DEFAULT_SUCCESS',
    LOGIN_USER_DEFAULT_FAILED: 'LOGIN_USER_DEFAULT_FAILED',
    LOGIN_USER_SALESFORCE: 'LOGIN_USER_SALESFORCE',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    GET_APPOINTMENTS_SUCCESS: 'GET_APPOINTMENTS_SUCCESS',
    GET_APPOINTMENT_BY_ID_SUCCESS: 'GET_APPOINTMENT_BY_ID_SUCCESS',
    GET_APPOINTMENT_BY_ID_FAILED: 'GET_APPOINTMENT_BY_ID_FAILED'
};
//# sourceMappingURL=actionTypes.js.map