export const actionTypes = {
    GET_OPPORTUNITIES: 'GET_OPPORTUNITIES',
    GET_OPPORTUNITIES_SUCCESS: 'GET_OPPORTUNITIES_SUCCESS',
    GET_OPPORTUNITY_BY_ID: 'GET_OPPORTUNITY_BY_ID',
    GET_OPPORTUNITY_BY_ID_SUCCESS: 'GET_OPPORTUNITY_BY_ID_SUCCESS',
    GET_OPPORTUNITY_BY_ID_FAILED: 'GET_OPPORTUNITY_BY_ID_FAILED',
    Filter_OPPORTUNITIES: 'Filter_OPPORTUNITIES',
    Filter_OPPORTUNITIES_SUCCESS: 'Filter_OPPORTUNITIES_SUCCESS',
    Filter_OPPORTUNITIES_FAILED: 'Filter_OPPORTUNITIES_FAILED',
    UPDATE_OPPORTUNITY: 'UPDATE_OPPORTUNITY',
    UPDATE_OPPORTUNITY_SUCCESS: 'UPDATE_OPPORTUNITY_SUCCESS',
    GET_TECHNOLOGIES: 'GET_TECHNOLOGIES',
    GET_TECHNOLOGIES_SUCCESS: 'GET_TECHNOLOGIES_SUCCESS',
};
//# sourceMappingURL=opportunity.action.types.js.map